### ISSUE TITLE
[Tracking issue] NHP DWI pipeline descriptors

### ISSUE THREAD

**Issue by nx10** [childmindresearch/niwrap#112]
niwrap should provide all interfaces needed to (in theory) support @kaitj s non-human primate DWI pipeline.

Anatomical:

- [x] NiftyReg: `reg_aladin` (http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftyReg)
- [x] Freesurfer: `python3 /freesurfer/mri_synthstrip`
- [x] https://github.com/childmindresearch/niwrap/issues/60
- [x] https://github.com/childmindresearch/niwrap/issues/32
- [x] https://github.com/childmindresearch/niwrap/issues/30
- [x] https://github.com/childmindresearch/niwrap/issues/26
- [x] https://github.com/childmindresearch/niwrap/pull/96
- [x] https://github.com/childmindresearch/niwrap/issues/31
- [x] https://github.com/childmindresearch/niwrap/issues/27

Diffusion:

- [x] MRTrix ?
  - [x] dwidenoise
  - [x] mrdegibbs
  - [x] dwiextract
  - [x] `dwibiascorrect` (this is just calling ANTS N4BiasCorrection) 
- [x] FSL
  - [x] https://github.com/childmindresearch/niwrap/pull/113
  - [x] `topup`
  - [x] `applytopup`
- [x] ANTS
  - [x] `antsRegistrationSyN.sh`
  - [x] `c3d`
  - [x] antsApplyTransforms  
- [x] ~This rotate_bvec [script](https://github.com/Washington-University/HCPpipelines/blob/master/global/scripts/Rotate_bvecs.sh)~ &rarr; Port to Python, this calls FSL `avscale` which should be wrapped instead

**Comment by kaitj** [comment]
Thanks - added a few more (editting your post directly). Some of these might be redundant with whats already been added in another issue or already created - I just haven't had a chance to check across them.

**Comment by nx10** [comment]
Ok added descriptors for everything here - many of them probably broken, but now we should be able to start implementing and fix as things break
